on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: true
        type: choice
        default: ubuntu-latest
        options:
        - ubuntu-slim
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-24.04-arm
        - ubuntu-22.04
        - ubuntu-22.04-arm
        #- windows-latest
        #- windows-2025
        #- windows-2022
        #- windows-11-arm
        - macos-latest
        - macos-26
        - macos-15
        - macos-14
        - macos-15-intel
        - macos-13
permissions: {}
jobs:
  main:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Dump github context
      env:
        CONTEXT: ${{ toJson(github) }}
      run: echo "$CONTEXT"

    - name: Dump env context
      env:
        CONTEXT: ${{ toJson(env) }}
      run: echo "$CONTEXT"

    - name: Dump vars context
      env:
        CONTEXT: ${{ toJson(vars) }}
      run: echo "$CONTEXT"

    - name: Dump job context
      env:
        CONTEXT: ${{ toJson(job) }}
      run: echo "$CONTEXT"

    # The jobs context is only available in reusable workflows, and can only be used to set outputs for a reusable workflow.
    # - name: Dump jobs context
    #   env:
    #     CONTEXT: ${{ toJson(jobs) }}
    #   run: echo "$CONTEXT"

    - name: Dump steps context
      env:
        CONTEXT: ${{ toJson(steps) }}
      run: echo "$CONTEXT"

    - name: Dump runner context
      env:
        CONTEXT: ${{ toJson(runner) }}
      run: echo "$CONTEXT"

    - name: Dump secrets context
      env:
        CONTEXT: ${{ toJson(secrets) }}
      run: echo "$CONTEXT"

    - name: Dump strategy context
      env:
        CONTEXT: ${{ toJson(strategy) }}
      run: echo "$CONTEXT"

    - name: Dump matrix context
      env:
        CONTEXT: ${{ toJson(matrix) }}
      run: echo "$CONTEXT"

    - name: Dump needs context
      env:
        CONTEXT: ${{ toJson(needs) }}
      run: echo "$CONTEXT"

    - name: Dump inputs context
      env:
        CONTEXT: ${{ toJson(inputs) }}
      run: echo "$CONTEXT"

    - name: IP Address
      run: curl -fsS https://cloudflare.com/cdn-cgi/trace

    - uses: zhangyoufu/action-debug@main
